name: Quality Check & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10 # Tu log dice que usas v10.11.1

      - uses: actions/setup-node@v4
        with:
          node-version: 22 # Tu log dice v22.22.0
          cache: "pnpm"

      - name: Install dependencies
        # Añadimos --no-frozen-lockfile por si hay cambios de arquitectura
        run: pnpm install --no-frozen-lockfile

      - name: Run Astro Check
        run: pnpm run check

      - name: Run Lint
        run: pnpm run lint

      - name: Build Project
        run: pnpm run build
